name: Full Stack Deployment (Main2 Branch)

on:
  push:
    branches: ['main2'] # Sirf main2 branch par trigger hoga

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Frontend build - Path './frontend' hai kyunki GitHub par folder wahi hai
      - name: Build & Push Frontend
        run: |
          docker build -t hrajpoot121/employee-frontend:latest .
          docker push hrajpoot121/employee-frontend:latest

      # Kubernetes Deployment
      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl rollout restart deployment employee-frontend
